name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and Attach Binary
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build solution
      run: |
        msbuild JSRTrainer.sln /p:Configuration=Release /p:Platform=x86 /p:LanguageStandard=stdcpp20

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./JSRTrainer/Release/JSRTrainer.exe
        asset_name: JSRTrainer.exe
        asset_content_type: application/octet-stream
